# editor configuration based on schema
"$schema" = 'https://starship.rs/config-schema.json'

# general configuration
add_newline = false
format = """
$username\
$hostname\
$battery\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$rust\
$sudo\
$cmd_duration\
$shell\
$character"""

[battery]
full_symbol = 'f'
charging_symbol = 'c'
discharging_symbol = 'd'
unknown_symbol = '?'
empty_symbol = 'empty'
format = '[$symbol\($percentage\)]($style) '

[[battery.display]]
threshold = 100
style = 'dimmed white'

[character]
success_symbol = '\$'
error_symbol = '[\$](bold red)'

[directory]
style = 'dimmed white'

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'white'

[python]
symbol = ''

[rust]
style = 'bold yellow'
symbol = ''

[shell]
disabled = false
