format = """
$battery\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$python\
$rust\
$dart\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

[battery]
disabled = false
format = " [$symbol$percentage]($style) "
full_symbol = "ğŸ¡ "
charging_symbol = "â‡‹ "
discharging_symbol = ""
unknown_symbol = "? "

[[battery.display]]
threshold = 30
style = "bold red"

[[battery.display]]
threshold = 100
style = "white"

[character]
success_symbol = '[%](bold white)'
error_symbol = '[%](bold red)'

[directory]
style = 'bold white'
truncation_symbol = '.../'

[directory.substitutions]
'Desktop' = 'â—† Desktop'
'Developer' = 'â—† Developer'
'Documents' = 'â—† Documents'
'Downloads' = 'â—† Downloads'
'Movies' = 'â—† Movies'
'Music' = 'â—† Music'
'Pictures' = 'â—† Pictures'

[fill]
symbol = '- '

[git_branch]
style = 'bold green'

[python]
symbol = 'py '
